import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    home: 'Home',
    about: 'About',
    login: 'Login',
    signup: 'Sign Up',
    dashboard: 'Dashboard',
    logout: 'Logout',
    profile: 'Profile',
    language: 'Language',
    success: 'Success',
    error: 'Error',
    loading: 'Loading...',
    
    // Auth
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account? ",
    signUpNow: 'Sign up now',
    orContinueWith: 'Or continue with',
    loginSuccessMessage: 'You have successfully logged in.',
    signInFailed: 'Sign In Failed',
    invalidCredentials: 'Invalid email or password',
    invalidEmail: 'Please enter a valid email address',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordsDontMatch: 'Passwords do not match',
    
    // Roles
    role: 'Role',
    selectRole: 'Select your role',
    youth: 'Youth',
    recruiter: 'Recruiter',
    admin: 'Admin',
    
    // Login Page
    loginTitle: 'Welcome to Talent Search Africa',
    loginSubtitle: 'Sign in to access your dashboard and discover opportunities',
    loginAs: 'Login as',
    emailAddress: 'Email Address',
    emailPlaceholder: 'name@example.com',
    recruiterQuestion: 'Looking to hire talent?',
    
    // Dashboard
    overview: 'Overview',
    connections: 'Connections',
    jobs: 'Jobs',
    applications: 'Applications',
    messaging: 'Messaging',
    
    // Youth Dashboard
    youthDashboard: 'Youth Dashboard',
    settingUpDashboard: 'Setting up your dashboard',
    dashboardLoadingSubtitle: 'Please hold on while we personalize your experience',
    monitorOpportunities: 'Monitor your opportunities, growth, and conversations',
    updateProfile: 'Update Profile',
    createCV: 'Create CV',
    uploadPortfolio: 'Upload Portfolio',
    welcome: 'Welcome!',
    profileProgress: 'Profile Progress',
    jobMatches: 'Job Matches',
    totalMatches: 'total matches',
    noJobMatchesYet: 'No job matches yet',
    pending: 'pending',
    noApplicationsYet: 'No applications yet',
    
    // Job Matches Page
    discoverOpportunities: 'Discover opportunities that match your profile',
    newMatchesToday: 'New matches today',
    savedJobs: 'Saved jobs',
    appliedJobs: 'Applied jobs',
    filters: 'Filters',
    search: 'Search',
    searchJobs: 'Search jobs...',
    category: 'Category',
    allCategories: 'All categories',
    location: 'Location',
    allLocations: 'All locations',
    jobType: 'Job Type',
    allTypes: 'All types',
    remote: 'Remote',
    hybrid: 'Hybrid',
    onSite: 'On-site',
    view: 'View',
    availableJobs: 'Available Jobs',
    noJobsFound: 'No jobs found',
    tryAdjustingFilters: 'Try adjusting your filters',
    noJobsAvailable: 'No jobs available at the moment',
    applied: 'Applied',
    viewDetails: 'View Details',
    save: 'Save',
    saved: 'Saved',
    applyNow: 'Apply Now',
    deleteApplication: 'Delete Application',
    deleteApplicationConfirm: 'Are you sure you want to delete your application for',
    thisActionCannotBeUndone: 'This action cannot be undone',
    cancel: 'Cancel',
    delete: 'Delete',
    applyFor: 'Apply for',
    submitApplication: 'Submit your application for this position',
    cvSelection: 'CV Selection',
    useExistingCV: 'Use existing CV',
    uploadNewCV: 'Upload new CV',
    chooseCV: 'Choose a CV',
    noCvAvailable: 'No CV available. Please upload a CV first.',
    uploadCvInstructions: 'Please upload a CV in your profile or create one using the Digital CV Builder.',
    clickToUpload: 'Click to upload',
    dragAndDrop: 'or drag and drop',
    fileTypes: 'PDF, DOC, DOCX (MAX. 10MB)',
    coverLetter: 'Cover Letter',
    writeCoverLetter: 'Write a cover letter...',
    submitting: 'Submitting...',
    uploadingCV: 'Uploading CV...',
    submitApplicationButton: 'Submit Application',
    applicationSubmitted: 'Application submitted successfully!',
    jobRemovedFromSaved: 'Job removed from saved',
    jobSavedSuccessfully: 'Job saved successfully',
    failedToSaveJob: 'Failed to save job',
    applicationNotFound: 'Application not found',
    applicationDeleted: 'Application deleted successfully',
    failedToDeleteApplication: 'Failed to delete application',
    viewCompleteJobDetails: 'View complete job details and requirements',
    jobDescription: 'Job Description',
    requirements: 'Requirements',
    qualifications: 'Qualifications',
    requiredSkills: 'Required Skills',
    department: 'Department',
    openings: 'Openings',
    applicationDeadline: 'Application Deadline',
    benefits: 'Benefits',
    saveJob: 'Save Job',
    posted: 'Posted',
    active: 'Active',
    networkConnections: 'Network connections',
    conversations: 'conversations',
    noMessagesYet: 'No messages yet',
    myProfile: 'My Profile',
    myPortfolio: 'My Portfolio',
    matches: 'Matches',
    skills: 'Skills',
    certificates: 'Certificates',
    reviewsAndRatings: 'Reviews & Ratings',
    aiAssistant: 'AI Assistant',
    analytics: 'Analytics',
    network: 'Network',
    settings: 'Settings',
    learning: 'Learning',
    
    // Reviews & Ratings
    reviewsAndRatingsTitle: 'Reviews & Ratings',
    reviewsAndRatingsSubtitle: 'View feedback and ratings from recruiters',
    noReviewsYet: 'You have not received any reviews yet',
    noReviewsDescription: 'Once recruiters interact with your profile or projects, their feedback will appear here.',
    noReviewsMotivation: 'Keep building your portfolio to attract more feedback!',
    overallPerformanceSummary: 'Overall Performance Summary',
    averageRating: 'Average Rating',
    basedOnReviews: 'Based on',
    verifiedRecruiterReview: 'verified recruiter review',
    verifiedRecruiterReviews: 'verified recruiter reviews',
    ratingDistribution: 'Rating Distribution',
    allReviews: 'All Reviews',
    review: 'Review',
    reviews: 'Reviews',
    feedback: 'Feedback',
    projectReviewed: 'Project Reviewed',
    reviewedOn: 'Reviewed on',
    
    // Portfolio
    getStarted: 'Get Started',
    uploadPortfolio: 'Upload Portfolio',
    uploadPortfolioDesc: 'Upload images, videos, project files.',
    selectFile: 'Select file',
    uploadSuccess: 'Upload successful',
    uploadError: 'Upload failed',
    uploading: 'Uploading...',
    
    // CV Builder
    digitalCVBuilder: 'Digital CV Builder',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    verify: 'Verify',
    pending: 'Pending',
    verified: 'Verified',
    rejected: 'Rejected',
    approve: 'Approve',
    reject: 'Reject',
    
    // Landing page translations
    showcaseYourTalent: 'Showcase Your Talent,',
    globalOpportunities: 'Global Opportunities',
    africaPremierPlatform: 'Africa\'s premier platform connecting talented youth with global opportunities',
    features: 'Features',
    verifiedSkills: 'Verified Skills',
    verifiedSkillsDesc: 'Get your skills verified by industry experts and stand out to recruiters worldwide.',
    globalReach: 'Global Reach',
    globalReachDesc: 'Connect with opportunities from companies and organizations around the world.',
    professionalReviews: 'Professional Reviews',
    professionalReviewsDesc: 'Receive feedback and endorsements from professionals in your field.',
    talentedYouth: 'Talented Youth',
    countries: 'Countries',
    ctaTitle: 'Ready to showcase your talent?',
    ctaSubtitle: 'Join thousands of talented youth and connect with global opportunities today.',
    joinAsTalent: 'Join as Talent',
    joinAsRecruiter: 'Join as Recruiter',
    imARecruiter: 'I\'m a Recruiter',
    getStartedFree: 'Get Started Free',
    forYouth: 'For Youth',
    forRecruiters: 'For Recruiters',
    contact: 'Contact',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    createProfile: 'Create Profile',
    findTalent: 'Find Talent',
    postReviews: 'Post Reviews',
    searchProfiles: 'Search Profiles',
    verifySkills: 'Verify Skills',

    // About page translations
    aboutTitle: 'About Talent Search Africa',
    aboutSubtitle: 'Talent Search Africa is a modern digital platform built to help young Africans showcase their skills, projects, and achievements to the world. Many youth have the talent but lack opportunities. This platform gives them visibility, verified credibility, and a way to connect directly with recruiters. Our goal is to empower Africa\'s youth by making it easy for them to build digital CVs, upload portfolios, verify certificates, and access global career opportunities.',
    ourMission: 'Our Mission',
    missionText: 'Our mission is to empower African youth by giving them a trusted and modern space to build their digital identity, showcase their talent, and access global job opportunities. We want to reduce unemployment, boost digital confidence, and increase verified African representation worldwide.',
    ourVision: 'Our Vision',
    visionText: 'We aim to become Africa\'s most reliable talent platform — a place where youth are recognized for creativity, innovation, and real-world skills. Our vision is to give African youth global visibility through verified skills and powerful digital tools.',
    whyUsTitle: 'Why Talent Search Africa Stands Out',
    builtForAfricanYouth: 'Built for African Youth',
    builtForAfricanYouthText: 'Talent Search Africa was created specifically for African youth. Unlike traditional job platforms, our system focuses on real portfolios, certificate verification, and direct access to recruiters. We combine creativity, technology, and trust to help youth build strong professional journeys.',
    simpleEffective: 'Simple & Effective',
    simpleEffectiveText: 'The platform is built to be simple, modern, and effective — a space where young people can showcase their best work, receive ratings and reviews, connect with companies, and access personalized guidance through an AI career assistant.',
    whoWeServe: 'Who We Serve',
    youthGraduates: 'Youth & Graduates',
    youthGraduatesText: 'Build digital identity and showcase projects.',
    recruitersEmployers: 'Recruiters & Employers',
    recruitersEmployersText: 'Access verified talent and post job opportunities.',
    universitiesInstitutions: 'Universities & Institutions',
    universitiesInstitutionsText: 'Partner with us to support student development.',
    ourStory: 'Our Story',
    storyText: 'Talent Search Africa was founded with a simple yet powerful vision: to bridge the gap between African talent and global opportunities. We recognized that many talented young Africans lack the platforms and tools to showcase their skills effectively. Our journey began with a commitment to create a space where creativity, innovation, and hard work are celebrated and rewarded.',
    getInTouch: 'Get In Touch',
    contactText: 'Have questions or want to get involved? We\'d love to hear from you. Reach out to us through email or our social media channels.',
    backToHome: 'Back to Home',
    empoweringAfricanYouth: 'Empowering African Youth',
    verifiedDigitalTalent: 'Verified Digital Talent',
    globalCareerAccess: 'Global Career Access',
    showcasingSkillsAcrossAfrica: 'Showcasing Skills Across Africa'
  },
  sw: {
    // Common
    home: 'Nyumbani',
    about: 'Kuhusu Sisi',
    login: 'Ingia',
    signup: 'Jisajili',
    dashboard: 'Dashibodi',
    logout: 'Toka',
    profile: 'Wasifu',
    language: 'Lugha',
    success: 'Mafanikio',
    error: 'Hitilafu',
    loading: 'Inapakia...',

    // Auth
    email: 'Barua pepe',
    password: 'Nenosiri',
    confirmPassword: 'Thibitisha Nenosiri',
    rememberMe: 'Nikumbuke',
    forgotPassword: 'Umesahau nenosiri?',
    dontHaveAccount: 'Huna akaunti? ',
    signUpNow: 'Jisajili sasa',
    orContinueWith: 'Au endelea na',
    loginSuccessMessage: 'Umeingia kikamilifu.',
    signInFailed: 'Kuingia Hakikufanikiwa',
    invalidCredentials: 'Barua pepe au nenosiri batili',
    invalidEmail: 'Tafadhali ingiza barua pepe sahihi',
    passwordRequired: 'Nenosiri linahitajika',
    passwordMinLength: 'Nenosiri lazima liwe na herufi angalau 6',
    passwordsDontMatch: 'Nenosiri halifanani',

    // Roles
    role: 'Jukumu',
    selectRole: 'Chagua jukumu lako',
    youth: 'Kijana',
    recruiter: 'Mwajiri',
    admin: 'Msimamizi',

    // Login Page
    welcomeBack: 'Karibu tena!',
    loginToAccount: 'Ingia kwenye akaunti yako',
    emailPlaceholder: 'jina@mfano.com',
    getStarted: 'Anza Sasa',
    uploadPortfolio: 'Pakia Portfolio',
    uploadPortfolioDesc: 'Pakia picha, video, faili za miradi.',
    selectFile: 'Chagua faili',
    uploadSuccess: 'Kupakia kumefanikiwa',
    uploadError: 'Kupakia kumeshindwa',
    uploading: 'Inapakia...',
    digitalCVBuilder: 'Kijenzi cha CV cha Kidijitali',
    adminDashboard: 'Dashibodi ya Msimamizi',
    verify: 'Thibitisha',
    pending: 'Inasubiri',
    verified: 'Imethibitishwa',
    rejected: 'Imekataliwa',
    approve: 'Kubali',
    reject: 'Kataa',
    overview: 'Muhtasari',
    connections: 'Uunganisho',
    jobs: 'Kazi',
    applications: 'Maombi',
    messaging: 'Ujumbe',
    
    // Youth Dashboard (Swahili)
    youthDashboard: 'Dashibodi ya Vijana',
    settingUpDashboard: 'Kusawazisha dashibodi yako',
    dashboardLoadingSubtitle: 'Tafadhali subiri tunapobadilisha uzoefu wako',
    monitorOpportunities: 'Fuata fursa zako, ukuaji, na mazungumzo',
    updateProfile: 'Sasisha Wasifu',
    createCV: 'Unda CV',
    uploadPortfolio: 'Pakia Portfolio',
    welcome: 'Karibu!',
    profileProgress: 'Maendeleo ya Wasifu',
    jobMatches: 'Mechi za Kazi',
    totalMatches: 'mechi jumla',
    noJobMatchesYet: 'Hakuna mechi za kazi bado',
    pending: 'inasubiri',
    noApplicationsYet: 'Hakuna maombi bado',
    networkConnections: 'Uunganisho wa mtandao',
    conversations: 'mazungumzo',
    noMessagesYet: 'Hakuna ujumbe bado',
    myProfile: 'Wasifu Wangu',
    myPortfolio: 'Portfolio Yangu',
    matches: 'Mechi',
    skills: 'Ujuzi',
    certificates: 'Vyeti',
    reviewsAndRatings: 'Mapitio na Makadirio',
    aiAssistant: 'Msaidizi wa AI',
    analytics: 'Takwimu',
    network: 'Mtandao',
    settings: 'Mipangilio',
    learning: 'Kujifunza',
    
    // Job Matches Page (Swahili)
    discoverOpportunities: 'Gundua fursa zinazolingana na wasifu wako',
    newMatchesToday: 'Mechi mpya leo',
    savedJobs: 'Kazi zilizohifadhiwa',
    appliedJobs: 'Kazi zilizotumwa',
    filters: 'Vichujio',
    search: 'Tafuta',
    searchJobs: 'Tafuta kazi...',
    category: 'Jamii',
    allCategories: 'Jamii zote',
    location: 'Eneo',
    allLocations: 'Maeneo yote',
    jobType: 'Aina ya Kazi',
    allTypes: 'Aina zote',
    remote: 'Kwa Mbali',
    hybrid: 'Mchanganyiko',
    onSite: 'Ofisini',
    view: 'Angalia',
    availableJobs: 'Kazi Zinazopatikana',
    noJobsFound: 'Hakuna kazi zilizopatikana',
    tryAdjustingFilters: 'Jaribu kubadilisha vichujio vyako',
    noJobsAvailable: 'Hakuna kazi zinazopatikana kwa sasa',
    applied: 'Imetumwa',
    viewDetails: 'Angalia Maelezo',
    save: 'Hifadhi',
    saved: 'Imehifadhiwa',
    applyNow: 'Tuma Sasa',
    deleteApplication: 'Futa Ombi',
    deleteApplicationConfirm: 'Je, una uhakika unataka kufuta ombi lako la',
    thisActionCannotBeUndone: 'Kitendo hiki hakiwezi kufutwa',
    cancel: 'Ghairi',
    delete: 'Futa',
    applyFor: 'Tuma kwa',
    submitApplication: 'Wasilisha ombi lako kwa nafasi hii',
    cvSelection: 'Uchaguzi wa CV',
    useExistingCV: 'Tumia CV iliyopo',
    uploadNewCV: 'Pakia CV mpya',
    chooseCV: 'Chagua CV',
    noCvAvailable: 'Hakuna CV inayopatikana. Tafadhali pakia CV kwanza.',
    uploadCvInstructions: 'Tafadhali pakia CV katika wasifu wako au unda moja kwa kutumia Kijenzi cha CV cha Kidijitali.',
    clickToUpload: 'Bofya kupakia',
    dragAndDrop: 'au buruta na uangushe',
    fileTypes: 'PDF, DOC, DOCX (KIKUBWA. 10MB)',
    coverLetter: 'Barua ya Kujitambulisha',
    writeCoverLetter: 'Andika barua ya kujitambulisha...',
    submitting: 'Inatumwa...',
    uploadingCV: 'CV inapakiwa...',
    submitApplicationButton: 'Wasilisha Ombi',
    applicationSubmitted: 'Ombi limewasilishwa kwa mafanikio!',
    jobRemovedFromSaved: 'Kazi imeondolewa kutoka kwa zilizohifadhiwa',
    jobSavedSuccessfully: 'Kazi imehifadhiwa kwa mafanikio',
    failedToSaveJob: 'Kuhifadhi kazi hakukufanikiwa',
    applicationNotFound: 'Ombi halijapatikana',
    applicationDeleted: 'Ombi limefutwa kwa mafanikio',
    failedToDeleteApplication: 'Kufuta ombi hakukufanikiwa',
    viewCompleteJobDetails: 'Angalia maelezo kamili ya kazi na mahitaji',
    jobDescription: 'Maelezo ya Kazi',
    requirements: 'Mahitaji',
    qualifications: 'Sifa',
    requiredSkills: 'Ujuzi Unaohitajika',
    department: 'Idara',
    openings: 'Nafasi',
    applicationDeadline: 'Mwisho wa Kutuma Maombi',
    benefits: 'Faida',
    saveJob: 'Hifadhi Kazi',
    posted: 'Imechapishwa',
    active: 'Inaendelea',
    
    // Reviews & Ratings (Swahili)
    reviewsAndRatingsTitle: 'Mapitio na Makadirio',
    reviewsAndRatingsSubtitle: 'Angalia maoni na makadirio kutoka kwa waajiri',
    noReviewsYet: 'Hujapokea mapitio yoyote bado',
    noReviewsDescription: 'Mara tu waajiri wakishiriki na wasifu wako au miradi, maoni yao yataonekana hapa.',
    noReviewsMotivation: 'Endelea kuunda portfolio yako ili kuvutia maoni zaidi!',
    overallPerformanceSummary: 'Muhtasari wa Utendakazi wa Jumla',
    averageRating: 'Makadirio ya Wastani',
    basedOnReviews: 'Kulingana na',
    verifiedRecruiterReview: 'mapitio ya mwajiri yaliyothibitishwa',
    verifiedRecruiterReviews: 'mapitio ya mwajiri yaliyothibitishwa',
    ratingDistribution: 'Usambazaji wa Makadirio',
    allReviews: 'Mapitio Yote',
    review: 'Mapitio',
    reviews: 'Mapitio',
    feedback: 'Maoni',
    projectReviewed: 'Mradi Uliopitiwa',
    reviewedOn: 'Iliopitiwa tarehe',

    // Landing page translations
    showcaseYourTalent: 'Onyesha Kipaji Chako',
    globalOpportunities: 'Fursa za Kimataifa',
    africaPremierPlatform: 'Jukwaa Bora la Afrika linalounganisha vijana wenye kipaji na fursa za kimataifa',
    features: 'Vipengele',
    verifiedSkills: 'Ustadi Uliothibitishwa',
    verifiedSkillsDesc: 'Pata ustadi wako uthibitishwe na wataalamu wa sekta na jitokeze kwa wawajiri duniani kote.',
    globalReach: 'Ufikiaji wa Kimataifa',
    globalReachDesc: 'Ungana na fursa kutoka kwa makampuni na mashirika duniani kote.',
    professionalReviews: 'Mapitio ya Kitaalamu',
    professionalReviewsDesc: 'Pata maoni na mapendekezo kutoka kwa wataalamu katika uwanja wako.',
    talentedYouth: 'Vijana Wenye Kipaji',
    countries: 'Nchi',
    ctaTitle: 'Uko tayari kuonyesha kipaji chako?',
    ctaSubtitle: 'Jiunge na maelfu ya vijana wenye kipaji na ungana na fursa za kimataifa leo.',
    joinAsTalent: 'Jiunge kama Kipaji',
    joinAsRecruiter: 'Jiunge kama Mwajiri',
    imARecruiter: 'Mimi ni Mwajiri',
    getStartedFree: 'Anza Bila Malipo',
    forYouth: 'Kwa Vijana',
    forRecruiters: 'Kwa Wawajiri',
    contact: 'Mawasiliano',
    termsOfService: 'Masharti ya Huduma',
    privacyPolicy: 'Sera ya Faragha',
    createProfile: 'Unda Wasifu',
    findTalent: 'Tafuta Kipaji',
    postReviews: 'Chapisha Mapitio',
    searchProfiles: 'Tafuta Wasifu',
    verifySkills: 'Thibitisha Ustadi',

    // About page translations
    aboutTitle: 'Kuhusu Talent Search Africa',
    aboutSubtitle: 'Talent Search Africa ni jukwaa la kidijitali la kisasa lililojengwa kusaidia vijana wa Afrika kuonyesha ujuzi wao, miradi, na mafanikio yao ulimwenguni. Vijana wengi wana kipaji lakini hawana fursa. Jukwaa hili huwapa mwonekano, uaminifu uliothibitishwa, na njia ya kuungana moja kwa moja na waajiri. Lengo letu ni kuwawezesha vijana wa Afrika kwa kuwafanya iwe rahisi kwao kujenga CV za kidijitali, kupakia portfolios, kuthibitisha vyeti, na kupata fursa za kazi za kimataifa.',
    ourMission: 'Dhamira Yetu',
    missionText: 'Dhamira yetu ni kuwawezesha vijana wa Afrika kwa kuwapa nafasi inayoaminika na ya kisasa ya kujenga utambulisho wao wa kidijitali, kuonyesha kipaji chao, na kupata fursa za kazi za kimataifa. Tunataka kupunguza ukosefu wa ajira, kuongeza imani ya kidijitali, na kuongeza uwakilishi uliothibitishwa wa Afrika ulimwenguni.',
    ourVision: 'Maono Yetu',
    visionText: 'Tunakusudia kuwa jukwaa la kipaji la kuaminika zaidi la Afrika — mahali ambapo vijana wanatambuliwa kwa ubunifu, uvumbuzi, na ujuzi wa ulimwengu halisi. Maono yetu ni kuwapa vijana wa Afrika mwonekano wa kimataifa kupitia ujuzi uliothibitishwa na zana zenye nguvu za kidijitali.',
    whyUsTitle: 'Kwa Nini Talent Search Africa Inatofautiana',
    builtForAfricanYouth: 'Imejengwa kwa Vijana wa Afrika',
    builtForAfricanYouthText: 'Talent Search Africa iliumbwa mahsusi kwa vijana wa Afrika. Tofauti na majukwaa ya kazi ya jadi, mfumo wetu unazingatia portfolios halisi, uthibitishaji wa vyeti, na ufikiaji wa moja kwa moja kwa waajiri. Tunachanganya ubunifu, teknolojia, na imani kusaidia vijana kujenga safari thabiti za kitaalamu.',
    simpleEffective: 'Rahisi na Yenye Ufanisi',
    simpleEffectiveText: 'Jukwaa limejengwa kuwa rahisi, la kisasa, na lenye ufanisi — nafasi ambapo watu wachanga wanaweza kuonyesha kazi yao bora, kupokea makadirio na mapitio, kuungana na makampuni, na kupata mwongozo maalum kupitia msaidizi wa kazi wa AI.',
    whoWeServe: 'Tunawahudumia Nani',
    youthGraduates: 'Vijana na Wahitimu',
    youthGraduatesText: 'Jenga utambulisho wa kidijitali na uonyeshe miradi.',
    recruitersEmployers: 'Waajiri na Waajiri',
    recruitersEmployersText: 'Pata kipaji kilichothibitishwa na uchapishe fursa za kazi.',
    universitiesInstitutions: 'Vyuo Vikuu na Taasisi',
    universitiesInstitutionsText: 'Shirikiana nasi kusaidia maendeleo ya wanafunzi.',
    ourStory: 'Hadithi Yetu',
    storyText: 'Talent Search Africa ilianzishwa na maono rahisi lakini yenye nguvu: kuunganisha pengo kati ya kipaji cha Afrika na fursa za kimataifa. Tulitambua kwamba vijana wengi wenye kipaji wa Afrika hawana majukwaa na zana za kuonyesha ujuzi wao kwa ufanisi. Safari yetu ilianza na kujitolea kuunda nafasi ambapo ubunifu, uvumbuzi, na kazi ngumu husherehekewa na kulipwa.',
    getInTouch: 'Wasiliana Nasi',
    contactText: 'Una maswali au unataka kuhusika? Tungependa kusikia kutoka kwako. Wasiliana nasi kupitia barua pepe au mifumo yetu ya kijamii.',
    backToHome: 'Rudi Nyumbani',
    empoweringAfricanYouth: 'Kuwawezesha Vijana wa Afrika',
    verifiedDigitalTalent: 'Kipaji cha Kidijitali Kiliothibitishwa',
    globalCareerAccess: 'Ufikiaji wa Kazi za Kimataifa',
    showcasingSkillsAcrossAfrica: 'Kuonyesha Ujuzi Katika Afrika'
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('language');
      return (saved === 'sw' ? 'sw' : 'en') as Language;
    } catch {
      return 'en';
    }
  });

  const toggleLanguage = () => {
    const newLang = language === 'en' ? 'sw' : 'en';
    setLanguage(newLang);
    try {
      localStorage.setItem('language', newLang);
    } catch {
      // ignore
    }
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};

export type { Language };

