import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// ==================== TYPES ====================

export type ReportType = 
  | 'executive_summary'
  | 'youth'
  | 'recruiter'
  | 'certificates'
  | 'reviews'
  | 'projects'
  | 'network'
  | 'flagged'
  | 'growth';

export interface ReportFilters {
  status?: 'verified' | 'pending' | 'suspended';
  rating?: number;
  certificateStatus?: 'verified' | 'pending' | 'rejected';
  projectStatus?: 'approved' | 'pending' | 'rejected';
  connectionStatus?: 'accepted' | 'pending' | 'declined';
}

export interface ReportOptions {
  includeCharts?: boolean;
  includeSummary?: boolean;
  customNotes?: string;
  filters?: ReportFilters;
}

export interface DateRange {
  start: Date;
  end: Date;
}

// ==================== HELPER FUNCTIONS ====================

const generateReportId = (): string => {
  return `RPT${Date.now().toString(36).toUpperCase()}${Math.floor(Math.random() * 1000)}`;
};

const formatDate = (date: Date): string => {
  return date.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
};

const formatDateTime = (date: Date): string => {
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

// Convert chart canvas to image
const chartToImage = async (chartElement: HTMLCanvasElement | null): Promise<string | null> => {
  if (!chartElement) return null;
  try {
    return chartElement.toDataURL('image/png');
  } catch (error) {
    console.error('Error converting chart to image:', error);
    return null;
  }
};

// Add chart placeholder (for future chart integration)
const addChartPlaceholder = (
  doc: jsPDF,
  title: string,
  description: string,
  startY: number
): number => {
  if (startY > 200) {
    doc.addPage();
    startY = 20;
  }
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 20, startY);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(description, 20, startY + 8);
  
  // Placeholder box for chart
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(250, 250, 250);
  doc.roundedRect(20, startY + 12, 170, 60, 3, 3, 'FD');
  
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.text('Chart visualization would appear here', 105, startY + 42, { align: 'center' });
  
  return startY + 80;
};

// ==================== COVER PAGE ====================

const addCoverPage = (
  doc: jsPDF,
  reportType: ReportType,
  dateRange: DateRange,
  adminName: string,
  reportId: string
): void => {
  // Background gradient effect (simulated with rectangles)
  doc.setFillColor(59, 130, 246); // Blue
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 80, 'F');
  
  // Platform logo area (placeholder)
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Talent Search Africa', 105, 30, { align: 'center' });
  
  // Report title
  const reportTitles: Record<ReportType, string> = {
    executive_summary: 'Executive Summary Report',
    youth: 'Youth Growth Report',
    recruiter: 'Recruiter Activity Report',
    certificates: 'Certificate Verification Report',
    reviews: 'Reviews & Ratings Report',
    projects: 'Portfolio & Project Report',
    network: 'Network Activity Report',
    flagged: 'Flagged Content & Moderation Report',
    growth: 'Growth & Analytics Report'
  };
  
  doc.setFontSize(20);
  doc.text(reportTitles[reportType] || 'Platform Report', 105, 50, { align: 'center' });
  
  // Date range
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `${formatDate(dateRange.start)} - ${formatDate(dateRange.end)}`,
    105,
    65,
    { align: 'center' }
  );
  
  // Metadata section
  doc.setFillColor(245, 245, 245);
  doc.rect(20, 100, 170, 100, 'F');
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(`Generated by: ${adminName}`, 30, 115);
  doc.text(`Generated at: ${formatDateTime(new Date())}`, 30, 125);
  doc.text(`Report ID: ${reportId}`, 30, 135);
  doc.text(`Date Range: ${formatDate(dateRange.start)} to ${formatDate(dateRange.end)}`, 30, 145);
  
  // Footer on cover
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(
    `Generated via Admin Console – #${reportId}`,
    105,
    doc.internal.pageSize.getHeight() - 15,
    { align: 'center' }
  );
  
  doc.addPage();
};

// ==================== EXECUTIVE SUMMARY ====================

const addExecutiveSummary = (
  doc: jsPDF,
  data: any,
  dateRange: DateRange
): number => {
  let yPos = 20;
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Executive Summary', 20, yPos);
  yPos += 15;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  
  const stats = data.stats || {};
  const analytics = data.analytics || {};
  
  // Generate summary text
  const summaryText = [
    `This report provides a comprehensive overview of the Talent Search Africa platform `,
    `for the period from ${formatDate(dateRange.start)} to ${formatDate(dateRange.end)}. `,
    `During this period, the platform has shown significant growth with a total of `,
    `${stats.totalYouth || 0} youth users and ${stats.totalRecruiters || 0} recruiters. `,
    `The platform has processed ${stats.pendingCertificates || 0} certificate verification `,
    `requests, with ${stats.totalProjects || 0} projects uploaded by users. `,
    `A total of ${stats.totalReviews || 0} reviews have been submitted, contributing to `,
    `the platform's reputation system. `,
    ``,
    `Key highlights include:`,
    `• User growth rate: ${analytics.growth?.youthGrowth?.[analytics.growth?.youthGrowth?.length - 1]?.count || 0} total youth users`,
    `• Certificate verification: ${stats.pendingCertificates || 0} pending, ${stats.totalCertificates || 0} total`,
    `• Platform engagement: ${stats.totalProjects || 0} projects, ${stats.totalReviews || 0} reviews`,
    `• Network activity: ${stats.totalConnections || 0} connections established`,
    `• Content moderation: ${stats.pendingReports || 0} reports requiring attention`
  ];
  
  const maxWidth = 170;
  summaryText.forEach((line) => {
    if (line.trim()) {
      const lines = doc.splitTextToSize(line, maxWidth);
      lines.forEach((textLine: string) => {
        if (yPos > 250) {
          doc.addPage();
          yPos = 20;
        }
        doc.text(textLine, 20, yPos);
        yPos += 6;
      });
    } else {
      yPos += 4;
    }
  });
  
  return yPos + 10;
};

// ==================== METRICS CARDS ====================

const addMetricsCards = (
  doc: jsPDF,
  data: any,
  startY: number
): number => {
  let yPos = startY;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Key Metrics', 20, yPos);
  yPos += 15;
  
  const stats = data.stats || {};
  const metrics = [
    { label: 'Total Youth', value: stats.totalYouth || 0 },
    { label: 'Total Recruiters', value: stats.totalRecruiters || 0 },
    { label: 'Certificates Uploaded', value: stats.totalCertificates || 0 },
    { label: 'Certificates Verified', value: (stats.totalCertificates || 0) - (stats.pendingCertificates || 0) },
    { label: 'Projects Submitted', value: stats.totalProjects || 0 },
    { label: 'Reviews Submitted', value: stats.totalReviews || 0 },
    { label: 'Active Users', value: (stats.totalYouth || 0) + (stats.totalRecruiters || 0) }
  ];
  
  const cardWidth = 85;
  const cardHeight = 30;
  const spacing = 5;
  let xPos = 20;
  
  metrics.forEach((metric, index) => {
    if (index > 0 && index % 2 === 0) {
      xPos = 20;
      yPos += cardHeight + spacing;
    }
    
    if (yPos + cardHeight > 270) {
      doc.addPage();
      yPos = 20;
      xPos = 20;
    }
    
    // Card background
    doc.setFillColor(240, 240, 240);
    doc.roundedRect(xPos, yPos, cardWidth, cardHeight, 3, 3, 'F');
    
    // Card border
    doc.setDrawColor(200, 200, 200);
    doc.roundedRect(xPos, yPos, cardWidth, cardHeight, 3, 3, 'S');
    
    // Metric label
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(metric.label, xPos + 5, yPos + 8);
    
    // Metric value
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(59, 130, 246);
    doc.text(metric.value.toString(), xPos + 5, yPos + 20);
    
    xPos += cardWidth + spacing;
  });
  
  return yPos + cardHeight + 15;
};

// ==================== DETAILED TABLES ====================

const addUserTable = (doc: jsPDF, users: any[], startY: number): number => {
  if (users.length === 0) return startY;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('User Details', 20, startY);
  
  const tableData = users.slice(0, 50).map(user => [
    user.userId?.substring(0, 8) || 'N/A',
    user.fullName || 'Unknown',
    user.role || 'N/A',
    user.isVerified ? 'Verified' : 'Pending',
    user.createdAt ? new Date(user.createdAt).toLocaleDateString() : 'N/A',
    user.isSuspended ? 'Suspended' : 'Active'
  ]);
  
  autoTable(doc, {
    startY: startY + 10,
    head: [['UID', 'Name', 'Role', 'Status', 'Joined', 'Last Active']],
    body: tableData,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [59, 130, 246] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 20, right: 20 }
  });
  
  return (doc as any).lastAutoTable.finalY + 10;
};

const addCertificateTable = (doc: jsPDF, certificates: any[], startY: number): number => {
  if (certificates.length === 0) return startY;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Certificate Verification Details', 20, startY);
  
  const tableData = certificates.slice(0, 50).map(cert => [
    cert.userName || 'Unknown',
    cert.certificateType || 'N/A',
    cert.submittedAt ? new Date(cert.submittedAt).toLocaleDateString() : 'N/A',
    cert.status || 'pending',
    cert.reviewerId ? 'Admin' : '-',
    cert.rejectionReason || '-'
  ]);
  
  autoTable(doc, {
    startY: startY + 10,
    head: [['Youth', 'Certificate Name', 'Uploaded', 'Status', 'Verified By', 'Reason (if rejected)']],
    body: tableData,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [34, 197, 94] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 20, right: 20 }
  });
  
  return (doc as any).lastAutoTable.finalY + 10;
};

const addReviewTable = (doc: jsPDF, reviews: any[], startY: number): number => {
  if (reviews.length === 0) return startY;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Reviews & Ratings Details', 20, startY);
  
  const tableData = reviews.slice(0, 50).map(review => [
    review.youthId?.substring(0, 8) || 'N/A',
    review.recruiterName || 'Unknown',
    (review.rating || 0).toString(),
    (review.reviewText || '').substring(0, 50) + (review.reviewText?.length > 50 ? '...' : ''),
    review.createdAt ? new Date(review.createdAt).toLocaleDateString() : 'N/A',
    review.status || 'submitted'
  ]);
  
  autoTable(doc, {
    startY: startY + 10,
    head: [['Youth', 'Recruiter', 'Rating', 'Comment', 'Date', 'Status']],
    body: tableData,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [234, 179, 8] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 20, right: 20 }
  });
  
  return (doc as any).lastAutoTable.finalY + 10;
};

const addProjectTable = (doc: jsPDF, projects: any[], startY: number): number => {
  if (projects.length === 0) return startY;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Project Uploads Details', 20, startY);
  
  const tableData = projects.slice(0, 50).map(project => [
    project.profileId?.substring(0, 8) || 'N/A',
    (project.title || 'Untitled').substring(0, 30),
    project.projectType || 'N/A',
    project.status || 'pending',
    project.isFeatured ? 'Yes' : 'No',
    project.createdAt ? new Date(project.createdAt).toLocaleDateString() : 'N/A'
  ]);
  
  autoTable(doc, {
    startY: startY + 10,
    head: [['Youth', 'Project Title', 'Type', 'Status', 'Featured', 'Date']],
    body: tableData,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [249, 115, 22] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 20, right: 20 }
  });
  
  return (doc as any).lastAutoTable.finalY + 10;
};

const addConnectionTable = (doc: jsPDF, connections: any[], startY: number): number => {
  if (connections.length === 0) return startY;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Network Connections', 20, startY);
  
  const tableData = connections.slice(0, 50).map(conn => [
    conn.fromUserName || conn.userId?.substring(0, 8) || 'N/A',
    conn.toUserName || conn.connectedUserId?.substring(0, 8) || 'N/A',
    conn.status || 'pending',
    conn.createdAt ? new Date(conn.createdAt).toLocaleDateString() : 'N/A',
    conn.acceptedAt ? new Date(conn.acceptedAt).toLocaleDateString() : '-'
  ]);
  
  autoTable(doc, {
    startY: startY + 10,
    head: [['From User', 'To User', 'Status', 'Created', 'Accepted']],
    body: tableData,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [236, 72, 153] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 20, right: 20 }
  });
  
  return (doc as any).lastAutoTable.finalY + 10;
};

const addFlaggedContentTable = (doc: jsPDF, reports: any[], startY: number): number => {
  if (reports.length === 0) return startY;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Flagged Content & Reports', 20, startY);
  
  const tableData = reports.slice(0, 50).map(report => [
    report.id?.substring(0, 8) || 'N/A',
    report.category || 'N/A',
    report.userName || 'Unknown',
    report.subject || 'N/A',
    report.status || 'open',
    report.resolvedAt ? new Date(report.resolvedAt).toLocaleDateString() : 'Pending'
  ]);
  
  autoTable(doc, {
    startY: startY + 10,
    head: [['Report ID', 'Type', 'Reported By', 'Target', 'Status', 'Resolution']],
    body: tableData,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [239, 68, 68] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 20, right: 20 }
  });
  
  return (doc as any).lastAutoTable.finalY + 10;
};

// ==================== ADMIN NOTES ====================

const addAdminNotes = (doc: jsPDF, notes: string, startY: number): number => {
  if (!notes || notes.trim() === '') return startY;
  
  if (startY > 250) {
    doc.addPage();
    startY = 20;
  }
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Admin Notes', 20, startY);
  startY += 10;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  
  const maxWidth = 170;
  const lines = doc.splitTextToSize(notes, maxWidth);
  
  lines.forEach((line: string) => {
    if (startY > 270) {
      doc.addPage();
      startY = 20;
    }
    doc.text(line, 20, startY);
    startY += 6;
  });
  
  return startY + 10;
};

// ==================== FOOTER ====================

const addFooter = (doc: jsPDF, reportId: string): void => {
  const pageCount = doc.getNumberOfPages();
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    
    // Page number
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    
    // Platform name
    doc.text(
      'Talent Search Africa',
      20,
      doc.internal.pageSize.getHeight() - 10
    );
    
    // Report ID
    doc.text(
      `Generated via Admin Console – #${reportId}`,
      doc.internal.pageSize.getWidth() - 20,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'right' }
    );
  }
};

// ==================== MAIN GENERATOR FUNCTION ====================

export const generateComprehensivePDFReport = async (
  reportType: ReportType,
  data: any,
  dateRange: DateRange,
  adminName: string,
  adminEmail: string,
  options: ReportOptions = {}
): Promise<Blob> => {
  const doc = new jsPDF();
  const reportId = generateReportId();
  
  // Cover page
  addCoverPage(doc, reportType, dateRange, adminName, reportId);
  
  let currentY = 20;
  
  // Executive Summary (for all report types)
  if (options.includeSummary !== false) {
    currentY = addExecutiveSummary(doc, data, dateRange);
    
    if (currentY > 250) {
      doc.addPage();
      currentY = 20;
    }
  }
  
  // Key Metrics Cards
  currentY = addMetricsCards(doc, data, currentY);
  
  if (currentY > 250) {
    doc.addPage();
    currentY = 20;
  }
  
  // Charts section (if enabled)
  if (options.includeCharts) {
    const analytics = data.analytics || {};
    
    // User Growth Chart
    if (analytics.growth?.youthGrowth) {
      currentY = addChartPlaceholder(
        doc,
        'User Growth Trend',
        'Shows the growth of youth users over the selected period',
        currentY
      );
    }
    
    // Skills Chart
    if (analytics.skills?.mostDemandedSkills) {
      currentY = addChartPlaceholder(
        doc,
        'Most Demanded Skills',
        'Top skills in demand across the platform',
        currentY
      );
    }
    
    // Reviews Chart
    if (data.reviews || analytics.reviews) {
      currentY = addChartPlaceholder(
        doc,
        'Reviews Breakdown',
        'Distribution of ratings and review activity',
        currentY
      );
    }
  }
  
  // Detailed tables based on report type
  switch (reportType) {
    case 'youth':
      if (data.users) {
        currentY = addUserTable(doc, data.users, currentY);
      }
      break;
    case 'recruiter':
      if (data.recruiters) {
        currentY = addUserTable(doc, data.recruiters, currentY);
      }
      break;
    case 'certificates':
      if (data.certificates) {
        currentY = addCertificateTable(doc, data.certificates, currentY);
      }
      break;
    case 'reviews':
      if (data.reviews) {
        currentY = addReviewTable(doc, data.reviews, currentY);
      }
      break;
    case 'projects':
      if (data.projects) {
        currentY = addProjectTable(doc, data.projects, currentY);
      }
      break;
    case 'network':
      if (data.connections) {
        currentY = addConnectionTable(doc, data.connections, currentY);
      }
      break;
    case 'flagged':
      if (data.reports) {
        currentY = addFlaggedContentTable(doc, data.reports, currentY);
      }
      break;
    case 'executive_summary':
    case 'growth':
      // For executive summary, include all relevant tables
      if (data.users) {
        currentY = addUserTable(doc, data.users.filter((u: any) => u.role === 'youth'), currentY);
        doc.addPage();
        currentY = 20;
      }
      if (data.certificates) {
        currentY = addCertificateTable(doc, data.certificates.slice(0, 30), currentY);
        doc.addPage();
        currentY = 20;
      }
      if (data.reviews) {
        currentY = addReviewTable(doc, data.reviews.slice(0, 30), currentY);
      }
      break;
  }
  
  // Admin Notes
  if (options.customNotes) {
    if (currentY > 250) {
      doc.addPage();
      currentY = 20;
    }
    currentY = addAdminNotes(doc, options.customNotes, currentY);
  }
  
  // Add footer to all pages
  addFooter(doc, reportId);
  
  return doc.output('blob');
};

