import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// ==================== REPORT TYPES ====================

export interface ReportData {
  title: string;
  generatedAt: Date;
  generatedBy: string;
  dateRange?: { start: Date; end: Date };
  data: any[];
  columns: Array<{ key: string; label: string }>;
  summary?: Record<string, any>;
}

export interface ReportOptions {
  format: 'pdf' | 'csv' | 'xlsx';
  template?: 'default' | 'detailed' | 'summary';
  includeCharts?: boolean;
  includeSummary?: boolean;
}

// ==================== PDF GENERATION ====================

export const generatePDFReport = async (
  reportData: ReportData,
  options: ReportOptions = { format: 'pdf', template: 'default' }
): Promise<Blob> => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(18);
  doc.text(reportData.title, 14, 20);
  
  // Add metadata
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${reportData.generatedAt.toLocaleString()}`, 14, 30);
  doc.text(`Generated by: ${reportData.generatedBy}`, 14, 35);
  
  if (reportData.dateRange) {
    doc.text(
      `Date Range: ${reportData.dateRange.start.toLocaleDateString()} - ${reportData.dateRange.end.toLocaleDateString()}`,
      14,
      40
    );
  }

  // Add summary if provided
  if (options.includeSummary && reportData.summary) {
    let yPos = 50;
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Summary', 14, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    Object.entries(reportData.summary).forEach(([key, value]) => {
      doc.text(`${key}: ${value}`, 14, yPos);
      yPos += 7;
    });
    yPos += 5;
  }

  // Add table
  const tableData = reportData.data.map(row =>
    reportData.columns.map(col => {
      const value = row[col.key];
      if (value instanceof Date) {
        return value.toLocaleDateString();
      }
      return value?.toString() || '';
    })
  );

  autoTable(doc, {
    head: [reportData.columns.map(col => col.label)],
    body: tableData,
    startY: options.includeSummary && reportData.summary ? 80 : 50,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [66, 139, 202] },
    alternateRowStyles: { fillColor: [245, 245, 245] }
  });

  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  return doc.output('blob');
};

// ==================== CSV GENERATION ====================

export const generateCSVReport = (
  reportData: ReportData,
  options: ReportOptions = { format: 'csv' }
): string => {
  const lines: string[] = [];
  
  // Add header
  lines.push(reportData.title);
  lines.push(`Generated: ${reportData.generatedAt.toLocaleString()}`);
  lines.push(`Generated by: ${reportData.generatedBy}`);
  
  if (reportData.dateRange) {
    lines.push(
      `Date Range: ${reportData.dateRange.start.toLocaleDateString()} - ${reportData.dateRange.end.toLocaleDateString()}`
    );
  }
  
  lines.push(''); // Empty line
  
  // Add summary if provided
  if (options.includeSummary && reportData.summary) {
    lines.push('Summary');
    Object.entries(reportData.summary).forEach(([key, value]) => {
      lines.push(`${key},${value}`);
    });
    lines.push(''); // Empty line
  }
  
  // Add column headers
  lines.push(reportData.columns.map(col => `"${col.label}"`).join(','));
  
  // Add data rows
  reportData.data.forEach(row => {
    const values = reportData.columns.map(col => {
      const value = row[col.key];
      if (value instanceof Date) {
        return `"${value.toLocaleDateString()}"`;
      }
      // Escape quotes and wrap in quotes
      const stringValue = (value?.toString() || '').replace(/"/g, '""');
      return `"${stringValue}"`;
    });
    lines.push(values.join(','));
  });
  
  return lines.join('\n');
};

// ==================== DOWNLOAD UTILITIES ====================

export const downloadReport = (
  content: Blob | string,
  filename: string,
  mimeType: string
): void => {
  if (typeof content === 'string') {
    // CSV or text
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } else {
    // PDF or other binary
    const url = URL.createObjectURL(content);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
};

// ==================== REPORT GENERATORS FOR SPECIFIC TYPES ====================

export const generateUserListReport = async (
  users: any[],
  generatedBy: string,
  options: ReportOptions = { format: 'pdf' }
): Promise<Blob | string> => {
  const reportData: ReportData = {
    title: 'User List Report',
    generatedAt: new Date(),
    generatedBy,
    data: users,
    columns: [
      { key: 'fullName', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'role', label: 'Role' },
      { key: 'country', label: 'Country' },
      { key: 'isVerified', label: 'Verified' },
      { key: 'isSuspended', label: 'Suspended' },
      { key: 'createdAt', label: 'Created At' }
    ],
    summary: {
      'Total Users': users.length,
      'Verified Users': users.filter(u => u.isVerified).length,
      'Suspended Users': users.filter(u => u.isSuspended).length
    }
  };

  if (options.format === 'pdf') {
    return await generatePDFReport(reportData, options);
  } else if (options.format === 'csv') {
    return generateCSVReport(reportData, options);
  } else {
    throw new Error('XLSX format not yet implemented');
  }
};

export const generateReviewAnalyticsReport = async (
  reviews: any[],
  generatedBy: string,
  options: ReportOptions = { format: 'pdf' }
): Promise<Blob | string> => {
  const averageRating = reviews.length > 0
    ? reviews.reduce((sum, r) => sum + (r.rating || 0), 0) / reviews.length
    : 0;

  const reportData: ReportData = {
    title: 'Review Analytics Report',
    generatedAt: new Date(),
    generatedBy,
    data: reviews,
    columns: [
      { key: 'recruiterName', label: 'Recruiter' },
      { key: 'youthId', label: 'Youth ID' },
      { key: 'rating', label: 'Rating' },
      { key: 'reviewText', label: 'Review' },
      { key: 'createdAt', label: 'Created At' }
    ],
    summary: {
      'Total Reviews': reviews.length,
      'Average Rating': averageRating.toFixed(2)
    }
  };

  if (options.format === 'pdf') {
    return await generatePDFReport(reportData, options);
  } else if (options.format === 'csv') {
    return generateCSVReport(reportData, options);
  } else {
    throw new Error('XLSX format not yet implemented');
  }
};

export const generateVerificationLogsReport = async (
  certificates: any[],
  generatedBy: string,
  options: ReportOptions = { format: 'pdf' }
): Promise<Blob | string> => {
  const reportData: ReportData = {
    title: 'Certificate Verification Logs',
    generatedAt: new Date(),
    generatedBy,
    data: certificates,
    columns: [
      { key: 'userName', label: 'User' },
      { key: 'certificateType', label: 'Certificate Type' },
      { key: 'status', label: 'Status' },
      { key: 'submittedAt', label: 'Submitted At' },
      { key: 'reviewedAt', label: 'Reviewed At' },
      { key: 'reviewerId', label: 'Reviewer' }
    ],
    summary: {
      'Total Certificates': certificates.length,
      'Verified': certificates.filter(c => c.status === 'verified').length,
      'Pending': certificates.filter(c => c.status === 'pending').length,
      'Rejected': certificates.filter(c => c.status === 'rejected').length
    }
  };

  if (options.format === 'pdf') {
    return await generatePDFReport(reportData, options);
  } else if (options.format === 'csv') {
    return generateCSVReport(reportData, options);
  } else {
    throw new Error('XLSX format not yet implemented');
  }
};

export const generateConnectionActivityReport = async (
  connections: any[],
  generatedBy: string,
  options: ReportOptions = { format: 'pdf' }
): Promise<Blob | string> => {
  const reportData: ReportData = {
    title: 'Connection Activity Report',
    generatedAt: new Date(),
    generatedBy,
    data: connections,
    columns: [
      { key: 'userId', label: 'User ID' },
      { key: 'connectedUserId', label: 'Connected User ID' },
      { key: 'status', label: 'Status' },
      { key: 'createdAt', label: 'Created At' },
      { key: 'acceptedAt', label: 'Accepted At' }
    ],
    summary: {
      'Total Connections': connections.length,
      'Accepted': connections.filter(c => c.status === 'accepted').length,
      'Pending': connections.filter(c => c.status === 'pending').length
    }
  };

  if (options.format === 'pdf') {
    return await generatePDFReport(reportData, options);
  } else if (options.format === 'csv') {
    return generateCSVReport(reportData, options);
  } else {
    throw new Error('XLSX format not yet implemented');
  }
};

export const generateGrowthMetricsReport = async (
  metrics: any,
  generatedBy: string,
  options: ReportOptions = { format: 'pdf' }
): Promise<Blob | string> => {
  const reportData: ReportData = {
    title: 'Growth Metrics Report',
    generatedAt: new Date(),
    generatedBy,
    data: [],
    columns: [],
    summary: metrics
  };

  if (options.format === 'pdf') {
    return await generatePDFReport(reportData, options);
  } else if (options.format === 'csv') {
    return generateCSVReport(reportData, options);
  } else {
    throw new Error('XLSX format not yet implemented');
  }
};

export const generatePlatformUsageReport = async (
  usage: any,
  generatedBy: string,
  options: ReportOptions = { format: 'pdf' }
): Promise<Blob | string> => {
  const reportData: ReportData = {
    title: 'Platform Usage Report',
    generatedAt: new Date(),
    generatedBy,
    data: [],
    columns: [],
    summary: usage
  };

  if (options.format === 'pdf') {
    return await generatePDFReport(reportData, options);
  } else if (options.format === 'csv') {
    return generateCSVReport(reportData, options);
  } else {
    throw new Error('XLSX format not yet implemented');
  }
};

export const generateReportsModerationLogsReport = async (
  reports: any[],
  generatedBy: string,
  options: ReportOptions = { format: 'pdf' }
): Promise<Blob | string> => {
  const reportData: ReportData = {
    title: 'Reports & Moderation Logs',
    generatedAt: new Date(),
    generatedBy,
    data: reports,
    columns: [
      { key: 'userName', label: 'Reporter' },
      { key: 'subject', label: 'Subject' },
      { key: 'category', label: 'Category' },
      { key: 'status', label: 'Status' },
      { key: 'createdAt', label: 'Created At' },
      { key: 'resolvedAt', label: 'Resolved At' }
    ],
    summary: {
      'Total Reports': reports.length,
      'Open': reports.filter(r => r.status === 'open').length,
      'Resolved': reports.filter(r => r.status === 'resolved').length
    }
  };

  if (options.format === 'pdf') {
    return await generatePDFReport(reportData, options);
  } else if (options.format === 'csv') {
    return generateCSVReport(reportData, options);
  } else {
    throw new Error('XLSX format not yet implemented');
  }
};

export const generateRecruiterActivityLogsReport = async (
  activity: any[],
  generatedBy: string,
  options: ReportOptions = { format: 'pdf' }
): Promise<Blob | string> => {
  const reportData: ReportData = {
    title: 'Recruiter Activity Logs',
    generatedAt: new Date(),
    generatedBy,
    data: activity,
    columns: [
      { key: 'recruiterId', label: 'Recruiter ID' },
      { key: 'action', label: 'Action' },
      { key: 'timestamp', label: 'Timestamp' },
      { key: 'details', label: 'Details' }
    ],
    summary: {
      'Total Activities': activity.length
    }
  };

  if (options.format === 'pdf') {
    return await generatePDFReport(reportData, options);
  } else if (options.format === 'csv') {
    return generateCSVReport(reportData, options);
  } else {
    throw new Error('XLSX format not yet implemented');
  }
};

export default {
  generatePDFReport,
  generateCSVReport,
  downloadReport,
  generateUserListReport,
  generateReviewAnalyticsReport,
  generateVerificationLogsReport,
  generateConnectionActivityReport,
  generateGrowthMetricsReport,
  generatePlatformUsageReport,
  generateReportsModerationLogsReport,
  generateRecruiterActivityLogsReport
};

